/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelArray.java
 *
 * Created on 9.12.2011, 19:35:55
 */
package cz.upce.inzui.z9.array;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.apache.log4j.Logger;

/**
 *
 * @author Marty
 */
public class PanelArray extends javax.swing.JPanel {

    private BufferedImage bulbOn = null;
    private BufferedImage bulbOff = null;
    protected static Logger logger = Logger.getLogger(PanelArray.class);
    private PanelBulb[][] map = new PanelBulb[ROWS][COLUMS];
    private static int ROWS = 5;
    private static int COLUMS = 5;

    public PanelArray() {
        this.setLayout(new GridLayout(ROWS, COLUMS, 2, 2));
        for (int x = 0; x < ROWS; x++) {
            for (int y = 0; y < COLUMS; y++) {
                map[x][y] = new PanelBulb(x, y, this);
                this.add(map[x][y]);
            }
        }
        this.setBackground(Color.gray);
        this.setMinimumSize(new Dimension(168, 168));
    }

    protected BufferedImage getBulbOn() {
        if (bulbOn == null) {
            bulbOn = loadImage(new File("imgs/BulbOn.png"));
        }
        return bulbOn;
    }

    protected BufferedImage getBulbOff() {
        if (bulbOff == null) {
            bulbOff = loadImage(new File("imgs/BulbOff.png"));
        }
        return bulbOff;
    }

    private BufferedImage loadImage(File f) {
        try {
            return ImageIO.read(f);
        } catch (IOException e) {
            logger.error(f.toString(), e);
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void EvtOnBulb(int row, int colum) {
        map[row][colum].negate();
        if (row + 1 < ROWS) {
            map[row + 1][colum].negate();
        }
        if (colum + 1 < COLUMS) {
            map[row][colum + 1].negate();
        }
        if (row - 1 >= 0) {
            map[row - 1][colum].negate();
        }
        if (colum - 1 >= 0) {
            map[row][colum - 1].negate();
        }

    }
}
